# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"config_file_path": "core.ipynb",
         "f": "core.ipynb",
         "config": "core.ipynb",
         "stats_can_regions": "core.ipynb",
         "stats_can_feature_by_ids_dir": "core.ipynb",
         "target_path": "core.ipynb",
         "target_features": "core.ipynb",
         "feature_encoding_map_dir": "core.ipynb",
         "polygon_path": "core.ipynb",
         "target_df_regions": "core.ipynb",
         "add_timestamp": "core.ipynb",
         "logging_setup": "core.ipynb",
         "get_target_df": "core.ipynb"}

modules = ["path_config.py",
           "logging.py",
           "TargetValuesPreprocessing.py"]

doc_url = "https://byz007.github.io/Helpseeker_nbdev/"

git_url = "https://github.com/byz007/Helpseeker_nbdev/tree/master/"

def custom_doc_links(name): return None
